from typing import TypedDict, Annotated
import operator

from langgraph.graph import StateGraph, END


# ============================================================
# SHARED STATE
# ============================================================

class ResearchState(TypedDict):
    """
    Shared state passed between all agents in the graph.

    Every node reads the current state and returns only the
    fields it wants to update.
    """

    # User's original research topic
    topic: str

    # Generated by the Planner
    sub_questions: list[str]

    # Generated by the Researcher.
    # operator.add ensures new research results are appended
    # instead of replacing existing results.
    research_notes: Annotated[list[dict], operator.add]

    # Generated by the Critic
    critique: str

    # Controls whether research should continue
    needs_more_research: bool

    # Generated by the Writer
    final_report: str

    # Prevents infinite feedback loops
    revision_count: int


# ============================================================
# PLANNER AGENT
# ============================================================

def planner_node(state: ResearchState) -> dict:
    """
    Breaks the main research topic into smaller questions.
    """

    print(f"\n[Planner] Breaking down topic: {state['topic']}")

    return {
        "sub_questions": [
            "What is the main concept?",
            "What are the important components?"
        ]
    }


# ============================================================
# RESEARCHER AGENT
# ============================================================

def researcher_node(state: ResearchState) -> dict:
    """
    Researches the questions generated by the Planner.

    For Day 2 this is only a stub.
    Day 3 will replace this with Tavily-powered research.
    """

    print(
        f"\n[Researcher] Researching "
        f"{len(state['sub_questions'])} questions"
    )

    # Stub research results
    findings = []

    for question in state["sub_questions"]:
        findings.append(
            {
                "question": question,
                "findings": f"Stub findings for: {question}"
            }
        )

    return {
        "research_notes": findings
    }


# ============================================================
# CRITIC AGENT
# ============================================================

def critic_node(state: ResearchState) -> dict:

    print(
        f"\n[Critic] Reviewing "
        f"{len(state['research_notes'])} research notes"
    )

    # Force one revision cycle
    if state["revision_count"] == 0:

        print("[Critic] Research incomplete. Requesting more research.")

        return {
            "needs_more_research": True,
            "critique": "Research needs additional detail.",
            "revision_count": state["revision_count"] + 1
        }

    print("[Critic] Research approved.")

    return {
        "needs_more_research": False,
        "critique": "",
        "revision_count": state["revision_count"]
    }

# ============================================================
# WRITER AGENT
# ============================================================

def writer_node(state: ResearchState) -> dict:
    """
    Produces the final report using accumulated research.
    """

    print("\n[Writer] Writing final report")

    report = f"""
Research Report
===============

Topic:
{state["topic"]}

Research Notes:
"""

    for note in state["research_notes"]:
        report += f"""

Question:
{note["question"]}

Findings:
{note["findings"]}
"""

    return {
        "final_report": report
    }


# ============================================================
# CONDITIONAL ROUTING
# ============================================================

def route_after_critic(state: ResearchState) -> str:
    """
    Determines whether to:

    Critic -> Researcher
    OR
    Critic -> Writer

    revision_count prevents infinite loops.
    """

    needs_more_research = state.get(
        "needs_more_research",
        False
    )

    revision_count = state.get(
        "revision_count",
        0
    )

    print(
        f"\n[Router] "
        f"needs_more_research={needs_more_research}, "
        f"revision_count={revision_count}"
    )

    if needs_more_research and revision_count < 3:

        print(
            "[Router] Sending task back "
            "to Researcher"
        )

        return "researcher"

    print(
        "[Router] Research approved. "
        "Sending task to Writer"
    )

    return "writer"


# ============================================================
# BUILD GRAPH
# ============================================================

def build_graph():

    graph = StateGraph(ResearchState)

    # Register nodes
    graph.add_node(
        "planner",
        planner_node
    )

    graph.add_node(
        "researcher",
        researcher_node
    )

    graph.add_node(
        "critic",
        critic_node
    )

    graph.add_node(
        "writer",
        writer_node
    )

    # Entry point
    graph.set_entry_point("planner")

    # Linear flow
    graph.add_edge(
        "planner",
        "researcher"
    )

    graph.add_edge(
        "researcher",
        "critic"
    )

    # Conditional feedback loop
    graph.add_conditional_edges(
        "critic",
        route_after_critic,
        {
            "researcher": "researcher",
            "writer": "writer",
        }
    )

    # Final node
    graph.add_edge(
        "writer",
        END
    )

    return graph.compile()


# ============================================================
# RUN APPLICATION
# ============================================================

if __name__ == "__main__":

    app = build_graph()

    print("\nGRAPH STRUCTURE:\n")
    print(app.get_graph().draw_mermaid())

    initial_state = {
        "topic": "How do multi-agent AI systems work?",
        "sub_questions": [],
        "research_notes": [],
        "critique": "",
        "needs_more_research": False,
        "revision_count": 0,
        "final_report": "",
    }

    result = app.invoke(initial_state)

    print("\n")
    print("=" * 60)
    print("FINAL REPORT")
    print("=" * 60)

    print(result["final_report"])